# Generated by Django 4.2.5 on 2023-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="label",
            field=models.CharField(default="c", max_length=1),
        ),
        migrations.AddField(
            model_name="question",
            name="background_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
