# Generated by Django 4.2.5 on 2023-11-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trials", "0002_option_label_question_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalitytype",
            name="background_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="personalitytype",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
