# Generated by Django 4.2.5 on 2023-11-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trials", "0003_personalitytype_background_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="background_image",
        ),
        migrations.AddField(
            model_name="question",
            name="background_image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
