# Generated by Django 4.2.5 on 2023-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trials", "0004_remove_question_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalitytype",
            name="images",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="personalitytype",
            name="background_image",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
